CREATE DATABASE rainTrack;
USE rainTrack;

CREATE TABLE users (
	id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE stations (
	id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    location VARCHAR(255) NOT NULL,
    MAC VARCHAR(17) NOT NULL UNIQUE
);

CREATE TABLE sensors (
	id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    cdStation INT NOT NULL,
    FOREIGN KEY (cdStation) REFERENCES stations(id)
);

CREATE TABLE readings (
	id INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
    cdSensor INT NOT NULL,
    temperature FLOAT,
    humidity FLOAT,
    pluviosity FLOAT,
	dateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cdSensor) REFERENCES sensors(id)
)